# Generated by Django 4.2.25 on 2025-11-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="environment name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("api", "API Testing"),
                            ("web", "WebUI Testing"),
                            ("app", "App Testing"),
                        ],
                        max_length=20,
                        verbose_name="environment category",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="environment config"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "environment",
                "verbose_name_plural": "environments",
                "db_table": "environments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("running", "处理中"),
                            ("completed", "处理完成"),
                            ("failed", "处理失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="task status",
                    ),
                ),
                (
                    "parsed_content",
                    models.TextField(blank=True, verbose_name="parsed content"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "db_table": "knowledge_base_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="project name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "db_table": "projects",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "can_edit",
                    models.BooleanField(default=False, verbose_name="can edit"),
                ),
                (
                    "can_delete",
                    models.BooleanField(default=False, verbose_name="can delete"),
                ),
                (
                    "can_execute_tests",
                    models.BooleanField(default=True, verbose_name="can execute tests"),
                ),
                (
                    "can_view_reports",
                    models.BooleanField(default=True, verbose_name="can view reports"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "project member",
                "verbose_name_plural": "project members",
                "db_table": "project_members",
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                (
                    "file",
                    models.FileField(upload_to="uploads/", verbose_name="file path"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="file size (bytes)")),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="file hash"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word"),
                            ("xlsx", "Excel"),
                            ("md", "Markdown"),
                            ("txt", "Text"),
                            ("json", "JSON"),
                            ("yaml", "YAML"),
                            ("xml", "XML"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="file type",
                    ),
                ),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="uploading",
                        max_length=20,
                        verbose_name="upload status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_files",
                "ordering": ["-created_at"],
            },
        ),
    ]
