# Generated by Django 4.2.25 on 2026-03-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebasefile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待入库"),
                    ("running", "正在入库"),
                    ("completed", "入库成功"),
                    ("failed", "入库失败"),
                ],
                db_index=True,
                default="pending",
                help_text='文件在向量数据库中的入库处理状态。只有"入库成功"状态的文件才会从向量数据库中删除。',
                max_length=20,
                verbose_name="RAG入库状态",
            ),
        ),
    ]
