# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_knowledgebasefile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("api", "API Testing"),
                    ("web", "Web Testing"),
                    ("app", "App Testing"),
                ],
                default="api",
                max_length=20,
                verbose_name="project type",
            ),
        ),
    ]
