# Generated by Django 4.2.25 on 2026-04-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_add_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("api", "API Testing"),
                    ("web", "Web Testing"),
                    ("app", "App Testing"),
                    ("perf", "Performance Testing"),
                ],
                default="api",
                max_length=20,
                verbose_name="project type",
            ),
        ),
    ]
