# Generated by Django 4.2.25 on 2025-11-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(max_length=500, verbose_name="endpoint path"),
                ),
                ("method", models.CharField(max_length=10, verbose_name="HTTP method")),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="summary"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=list, verbose_name="parameters"
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="request body"
                    ),
                ),
                (
                    "responses",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="responses"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                (
                    "operation_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="operation id"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "API endpoint",
                "verbose_name_plural": "API endpoints",
                "db_table": "api_endpoints",
            },
        ),
        migrations.CreateModel(
            name="APISpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("running", "处理中"),
                            ("completed", "处理完成"),
                            ("failed", "处理失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="task status",
                    ),
                ),
                (
                    "spec_type",
                    models.CharField(
                        choices=[
                            ("swagger", "Swagger/OpenAPI"),
                            ("postman", "Postman Collection"),
                            ("raml", "RAML"),
                            ("api_blueprint", "API Blueprint"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        default="swagger",
                        max_length=20,
                        verbose_name="specification type",
                    ),
                ),
                (
                    "spec_name",
                    models.CharField(
                        blank=True,
                        help_text="API规范名称",
                        max_length=200,
                        verbose_name="specification name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="API规范描述", verbose_name="description"
                    ),
                ),
                (
                    "parsed_content",
                    models.TextField(blank=True, verbose_name="parsed content"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "db_table": "api_specifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APITestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_case_type",
                    models.CharField(
                        choices=[
                            ("endpoint", "Endpoint Test Case"),
                            ("scenario", "Scenario Test Case"),
                        ],
                        default="endpoint",
                        help_text="测试用例类型：端点测试或场景测试",
                        max_length=20,
                        verbose_name="test case type",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="test case title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "test_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive Test"),
                            ("negative", "Negative Test"),
                            ("boundary", "Boundary Test"),
                            ("security", "Security Test"),
                        ],
                        default="positive",
                        help_text="测试类型（仅端点测试用例需要）",
                        max_length=20,
                        verbose_name="test type",
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="request data"
                    ),
                ),
                (
                    "expected_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="expected response"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="variables"
                    ),
                ),
                (
                    "expected_status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="expected status code"
                    ),
                ),
                (
                    "assertions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="assertions"
                    ),
                ),
                (
                    "script_content",
                    models.TextField(blank=True, verbose_name="script content"),
                ),
                (
                    "mapped_apis",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="映射的API接口（仅场景测试用例需要）",
                        verbose_name="mapped apis",
                    ),
                ),
                (
                    "api_specifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="相关的API规范信息（仅场景测试用例需要）",
                        verbose_name="api specifications",
                    ),
                ),
                ("timeout", models.IntegerField(default=30, verbose_name="timeout")),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="retry count"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "API test case",
                "verbose_name_plural": "API test cases",
                "db_table": "api_test_cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APITestCaseExecutionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="用例名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "执行通过"),
                            ("failed", "执行失败"),
                            ("error", "执行错误"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="执行日志")),
                (
                    "httprunner_result",
                    models.TextField(default="", verbose_name="HttpRunner结果"),
                ),
            ],
            options={
                "verbose_name": "API单用例执行详情",
                "verbose_name_plural": "API单用例执行详情",
                "db_table": "api_test_case_execution_details",
                "ordering": ["-execution__created_at"],
            },
        ),
        migrations.CreateModel(
            name="APITestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exec_type",
                    models.CharField(
                        choices=[("case", "单用例执行"), ("suite", "套件执行")],
                        max_length=10,
                        verbose_name="执行类型",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="执行名称")),
                ("description", models.TextField(blank=True, verbose_name="执行描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "执行通过"),
                            ("failed", "执行失败"),
                            ("error", "执行错误"),
                            ("stopped", "已停止"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="执行进度")),
                ("total_steps", models.IntegerField(default=0, verbose_name="总步骤数")),
                ("success_steps", models.IntegerField(default=0, verbose_name="成功步骤数")),
                ("failure_steps", models.IntegerField(default=0, verbose_name="失败步骤数")),
                ("error_steps", models.IntegerField(default=0, verbose_name="错误步骤数")),
                (
                    "execution_log",
                    models.TextField(blank=True, null=True, verbose_name="执行日志"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动触发"),
                            ("schedule", "计划任务"),
                            ("api", "API调用"),
                            ("llm", "LLM执行"),
                            ("jenkins", "Jenkins"),
                            ("ci_cd", "CI/CD"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="任务ID"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                (
                    "log_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="日志路径"
                    ),
                ),
                (
                    "report_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="报告路径"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "API测试执行记录",
                "verbose_name_plural": "API测试执行记录",
                "db_table": "api_test_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APITestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="测试套件名称")),
                ("description", models.TextField(blank=True, verbose_name="测试套件描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "激活"),
                            ("inactive", "停用"),
                            ("archived", "已归档"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "API测试套件",
                "verbose_name_plural": "API测试套件",
                "db_table": "api_test_suites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APITestSuiteExecutionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cases",
                    models.PositiveIntegerField(default=0, verbose_name="总用例数"),
                ),
                (
                    "passed_cases",
                    models.PositiveIntegerField(default=0, verbose_name="通过用例数"),
                ),
                (
                    "failed_cases",
                    models.PositiveIntegerField(default=0, verbose_name="失败用例数"),
                ),
                (
                    "skipped_cases",
                    models.PositiveIntegerField(default=0, verbose_name="跳过用例数"),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="执行日志")),
                (
                    "allure_report",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Allure报告路径"
                    ),
                ),
                (
                    "execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suite_execution_detail",
                        to="api_testing.apitestexecution",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_testing.apitestsuite",
                        verbose_name="测试套件",
                    ),
                ),
            ],
            options={
                "verbose_name": "API套件执行详情",
                "verbose_name_plural": "API套件执行详情",
                "db_table": "api_test_suite_execution_details",
                "ordering": ["-execution__created_at"],
            },
        ),
        migrations.CreateModel(
            name="APITestSuiteCaseExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="用例名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "执行通过"),
                            ("failed", "执行失败"),
                            ("error", "执行错误"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="执行日志")),
                (
                    "httprunner_result",
                    models.TextField(default="", verbose_name="HttpRunner结果"),
                ),
                (
                    "suite_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_executions",
                        to="api_testing.apitestsuiteexecutiondetail",
                        verbose_name="套件执行详情",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_testing.apitestcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "API套件用例执行明细",
                "verbose_name_plural": "API套件用例执行明细",
                "db_table": "api_test_suite_case_executions",
                "ordering": ["suite_execution", "test_case"],
            },
        ),
    ]
