# Generated by Django 4.2.25 on 2025-11-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("api_testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitestsuite",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="apitestsuite",
            name="test_cases",
            field=models.ManyToManyField(
                blank=True,
                related_name="test_suites",
                to="api_testing.apitestcase",
                verbose_name="测试用例",
            ),
        ),
    ]
