# Generated by Django 4.2.25 on 2025-11-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_testing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitestsuite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建用户",
            ),
        ),
        migrations.AddField(
            model_name="apitestexecution",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.environment",
                verbose_name="执行环境",
            ),
        ),
        migrations.AddField(
            model_name="apitestexecution",
            name="executor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="执行者",
            ),
        ),
        migrations.AddField(
            model_name="apitestexecution",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="apitestcaseexecutiondetail",
            name="execution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_execution_detail",
                to="api_testing.apitestexecution",
                verbose_name="执行记录",
            ),
        ),
        migrations.AddField(
            model_name="apitestcaseexecutiondetail",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api_testing.apitestcase",
                verbose_name="测试用例",
            ),
        ),
        migrations.AddField(
            model_name="apitestcase",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_api_test_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apitestcase",
            name="endpoint",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的API端点（仅端点测试用例需要）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="api_testing.apiendpoint",
            ),
        ),
        migrations.AddField(
            model_name="apitestcase",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_test_cases",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="apispecification",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_api_specs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apispecification",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_specs",
                to="projects.project",
                verbose_name="project",
            ),
        ),
        migrations.AddField(
            model_name="apispecification",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_specifications",
                to="projects.uploadedfile",
                verbose_name="uploaded file",
            ),
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="spec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="api_testing.apispecification",
            ),
        ),
        migrations.AddIndex(
            model_name="apitestsuite",
            index=models.Index(
                fields=["user", "project"], name="api_test_su_user_id_6c1fce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apitestsuite",
            index=models.Index(fields=["status"], name="api_test_su_status_f2f686_idx"),
        ),
        migrations.AddIndex(
            model_name="apitestsuite",
            index=models.Index(
                fields=["created_at"], name="api_test_su_created_ab7e89_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apitestcase",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("endpoint__isnull", False), ("test_case_type", "endpoint")
                        ),
                        models.Q(
                            ("endpoint__isnull", True), ("test_case_type", "scenario")
                        ),
                        _connector="OR",
                    )
                ),
                name="endpoint_required_for_endpoint_test_cases",
            ),
        ),
        migrations.AddConstraint(
            model_name="apispecification",
            constraint=models.UniqueConstraint(
                fields=("project", "uploaded_file"),
                name="unique_apispec_per_project_file",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apiendpoint",
            unique_together={("spec", "path", "method")},
        ),
    ]
