# Generated by Django 4.2.25 on 2026-04-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_testing", "0011_apiendpoint_module"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiendpoint",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "API endpoint",
                "verbose_name_plural": "API endpoints",
            },
        ),
        migrations.AlterModelOptions(
            name="apitestcase",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "API test case",
                "verbose_name_plural": "API test cases",
            },
        ),
    ]
