# Generated by Django 4.2.25 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_testing", "0012_alter_apiendpoint_options_alter_apitestcase_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitestexecution",
            name="exec_type",
            field=models.CharField(
                choices=[
                    ("case", "单用例执行"),
                    ("scenario", "场景执行"),
                    ("suite", "套件执行"),
                ],
                max_length=10,
                verbose_name="执行类型",
            ),
        ),
    ]
