# Generated by Django 4.2.25 - 仅 Channel；Rule 在 0002 创建

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='渠道名称')),
                ('channel_type', models.CharField(choices=[('dingtalk', '钉钉'), ('wechat_work', '企微')], db_index=True, default='dingtalk', max_length=20, verbose_name='类型')),
                ('webhook_url', models.URLField(max_length=2000, verbose_name='Webhook 地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知渠道',
                'verbose_name_plural': '通知渠道',
                'db_table': 'notifications_channel',
                'ordering': ['-created_at'],
            },
        ),
    ]
