# Generated by Django 4.2.25 on 2026-03-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_emailconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationchannel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "通知对象",
                "verbose_name_plural": "通知对象",
            },
        ),
        migrations.AlterField(
            model_name="notificationchannel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="接收群组名称"),
        ),
    ]
