# Generated by Django 4.2.25 on 2026-04-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_fix_receiver_project_id_from_tasks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationreceiver",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "通知接收对象",
                "verbose_name_plural": "通知接收对象",
            },
        ),
        migrations.AlterField(
            model_name="notificationreceiver",
            name="name",
            field=models.CharField(max_length=100, verbose_name="通知组名称"),
        ),
    ]
