# Generated by Django 4.2.25 on 2025-11-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="任务描述"),
                ),
                (
                    "suite_type",
                    models.CharField(
                        choices=[("web", "Web测试"), ("app", "App测试"), ("api", "API测试")],
                        max_length=10,
                        verbose_name="测试类型",
                    ),
                ),
                (
                    "suite_ids",
                    models.JSONField(
                        default=list,
                        help_text="存储多个测试套件ID的JSON数组",
                        verbose_name="测试套件ID列表",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="格式: 分 时 日 月 周 (如: 0 9 * * 1-5 表示工作日9点执行)",
                        max_length=100,
                        verbose_name="Cron表达式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("paused", "暂停"),
                            ("disabled", "禁用"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次执行时间"),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次执行时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.environment",
                        verbose_name="执行环境",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "定时任务",
                "verbose_name_plural": "定时任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "result_log",
                    models.TextField(blank=True, null=True, verbose_name="执行日志"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("total_cases", models.IntegerField(default=0, verbose_name="总用例数")),
                ("passed_cases", models.IntegerField(default=0, verbose_name="通过用例数")),
                ("failed_cases", models.IntegerField(default=0, verbose_name="失败用例数")),
                ("skipped_cases", models.IntegerField(default=0, verbose_name="跳过用例数")),
                (
                    "report_url",
                    models.URLField(blank=True, null=True, verbose_name="测试报告URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="scheduled_tasks.scheduledtask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务执行日志",
                "verbose_name_plural": "任务执行日志",
                "ordering": ["-start_time"],
            },
        ),
    ]
