# Generated by Django 4.2.25 on 2025-11-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduled_tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建用户",
            ),
        ),
        migrations.AddIndex(
            model_name="taskexecutionlog",
            index=models.Index(
                fields=["task", "start_time"], name="scheduled_t_task_id_4c4abe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskexecutionlog",
            index=models.Index(fields=["status"], name="scheduled_t_status_07cd71_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["suite_type"], name="scheduled_t_suite_t_3f786c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(fields=["status"], name="scheduled_t_status_26dee7_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["next_run_time"], name="scheduled_t_next_ru_83cf47_idx"
            ),
        ),
    ]
