<template>
  <div v-if="snapshot && Object.keys(snapshot).length" class="evidence-content">
    <div class="evidence-section"><h5>访问路径</h5><el-tag v-for="path in snapshot.visited_paths || []" :key="path" class="path-tag" effect="plain">{{ path }}</el-tag><span v-if="!(snapshot.visited_paths || []).length" class="muted">尚无页面路径</span></div>
    <div class="evidence-section"><h5>页面与关键区域</h5><el-table :data="snapshot.page_states || []" size="small" max-height="240"><el-table-column prop="name" label="页面" min-width="130" /><el-table-column prop="path" label="路径" min-width="150" /><el-table-column label="关键区域" min-width="180"><template #default="{ row }">{{ (row.key_regions || []).join('、') || '—' }}</template></el-table-column></el-table></div>
    <div class="evidence-section"><h5>关键元素</h5><el-collapse><el-collapse-item v-for="(element, index) in snapshot.elements || []" :key="`${element.page_name}-${element.visible_name}-${index}`" :title="`${element.page_name || '页面'} · ${element.visible_name || '未命名元素'}`"><p>角色：{{ element.role || '未识别' }}</p><p v-if="Object.keys(element.stable_attributes || {}).length">稳定属性：{{ attributeText(element.stable_attributes) }}</p><div v-if="element.candidate_locators?.length"><span class="muted">候选定位器</span><pre v-for="locator in element.candidate_locators" :key="locator">{{ locator }}</pre></div></el-collapse-item></el-collapse></div>
    <div class="evidence-section"><h5>场景步骤证据</h5><el-table :data="evidenceRows" size="small" max-height="260"><el-table-column prop="stepId" label="步骤" width="86" /><el-table-column prop="status" label="证据状态" width="110"><template #default="{ row }"><el-tag :type="row.status === 'confirmed' ? 'success' : row.status === 'partial' || row.status === 'partially_confirmed' ? 'warning' : 'danger'" size="small">{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column prop="reason" label="说明" min-width="220" /></el-table></div>
    <div class="evidence-section operation-ledger"><h5>AI 整理的页面操作台账</h5><p class="muted">此处为探索与流程验证期间整理的页面结果，不等于 Python 脚本已实际调试通过。</p><template v-if="hasOperationLedger"><p v-if="snapshot.exploration_namespace">本轮数据命名空间：<code>{{ snapshot.exploration_namespace }}</code></p><el-table v-if="operationActions.length" :data="operationActions" size="small" max-height="280"><el-table-column prop="stepId" label="步骤" width="86" /><el-table-column prop="operationLabel" label="操作" width="86" /><el-table-column prop="scopeLabel" label="范围" width="100" /><el-table-column label="结果状态" width="100"><template #default="{ row }"><el-tag :type="operationStatusType(row.status)" size="small">{{ operationStatusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column prop="target" label="目标" min-width="140" /><el-table-column prop="result" label="结果说明" min-width="180" /><el-table-column prop="evidencePath" label="证据路径" min-width="160" /></el-table><p v-else class="muted">尚无页面操作台账。</p><el-alert v-if="cleanup.hasRecord" class="cleanup-alert" :type="cleanup.type" :closable="false" show-icon :title="cleanupTitle" /><div v-if="cleanup.hasRecord && (cleanup.residuals.length || snapshot.exploration_namespace)" class="cleanup-details"><p v-if="snapshot.exploration_namespace">人工检查命名空间：<code>{{ snapshot.exploration_namespace }}</code></p><p v-if="cleanup.residuals.length">残留数据：</p><ul v-if="cleanup.residuals.length"><li v-for="residual in cleanup.residuals" :key="residual">{{ residual }}</li></ul></div><p v-else-if="!cleanup.hasRecord" class="muted">尚无清理记录。</p></template><el-empty v-else description="尚无操作台账或清理记录" :image-size="56" /></div>
    <div v-if="completion.status" class="evidence-section checkpoint"><h5>探索与流程验证情况</h5><p><el-tag :type="completionType" size="small">{{ completionLabel }}</el-tag></p><el-table v-if="missingTargets.length" :data="missingTargets" size="small" max-height="240"><el-table-column prop="target" label="待确认目标" min-width="150" /><el-table-column label="类型" width="130"><template #default="{ row }">{{ targetKindLabel(row.kind) }}</template></el-table-column><el-table-column prop="reason" label="原因 / 后续处理" min-width="240" /></el-table><p v-if="completion.budget_exhausted">探索轮次预算已用尽，平台不会继续猜测或扩大已确认的目标范围。</p><p class="muted">探索或流程验证完成不代表 Python 脚本已实际调试通过；实际操作台账和清理结果会在服务端提供后单独展示。</p></div>
    <div v-if="checkpoints.length" class="evidence-section"><h5>探索检查点</h5><el-table :data="checkpoints" size="small" max-height="200"><el-table-column prop="call_index" label="调用序号" width="100" /><el-table-column prop="tool_name" label="工具" min-width="180" /><el-table-column label="结果" width="110"><template #default="{ row }"><el-tag :type="row.status === 'succeeded' ? 'success' : 'danger'" size="small">{{ row.status === 'succeeded' ? '成功' : '失败' }}</el-tag></template></el-table-column></el-table></div>
  <el-alert v-if="snapshot.unresolved_steps?.length" type="warning" :closable="false" show-icon :title="`未确认步骤：${snapshot.unresolved_steps.join('、')}`" />
    <div class="evidence-section stats"><h5>探索统计</h5><span>工具调用 {{ toolStats.total_tool_calls || 0 }}</span><span>失败调用 {{ toolStats.failed_tool_calls || 0 }}</span><span>耗时 {{ formatDuration(toolStats.duration_seconds) }}</span><span v-if="hasWriteToolStats">平台计数：潜在写入工具调用 {{ toolStats.potential_write_tool_calls || 0 }}，已拦截写入工具调用 {{ toolStats.blocked_write_tool_calls || 0 }}。潜在写入不代表业务提交成功。</span><span v-if="toolStats.termination_reason">结束原因：{{ toolStats.termination_reason }}</span></div>
  </div>
  <el-empty v-else description="页面探索尚未完成" :image-size="70" />
</template>

<script setup>
import { computed } from 'vue'
import { explorationCleanupPresentation } from '@/composables/webUIScriptGenerationPresentation'
const props = defineProps({ snapshot: { type: Object, default: () => ({}) }, toolStats: { type: Object, default: () => ({}) } })
const evidenceRows = computed(() => Object.entries(props.snapshot?.step_evidence || {}).map(([stepId, item]) => ({ stepId, status: item.status || 'unresolved', reason: item.reason || (item.element_names || []).join('、') || '—' })))
const completion = computed(() => props.snapshot?.completion || {})
const missingTargets = computed(() => Array.isArray(completion.value?.missing_targets) ? completion.value.missing_targets : [])
const checkpoints = computed(() => Array.isArray(props.snapshot?.checkpoints) ? props.snapshot.checkpoints : [])
const operationActions = computed(() => (Array.isArray(props.snapshot?.exploration_actions) ? props.snapshot.exploration_actions : []).map((item, index) => ({ stepId: item?.step_id || `#${index + 1}`, operation: item?.operation || '', operationLabel: operationLabel(item?.operation), scopeLabel: operationScopeLabel(item?.scope), status: item?.status || 'unknown', target: item?.target || '—', evidencePath: item?.evidence_path || '—', result: item?.result || '—' })))
const cleanup = computed(() => explorationCleanupPresentation(props.snapshot))
const hasOperationLedger = computed(() => Boolean(props.snapshot?.exploration_namespace) || Array.isArray(props.snapshot?.exploration_actions) || cleanup.value.hasRecord)
const hasWriteToolStats = computed(() => props.toolStats?.potential_write_tool_calls !== undefined || props.toolStats?.blocked_write_tool_calls !== undefined)
const completionLabel = computed(() => ({ complete: props.snapshot?.exploration_explicit_read_only ? '只读页面探索完成（未提交业务操作）' : '目标范围探索完成', needs_targeted_exploration: '需要补充探索', needs_user_decision: '需要业务决策', blocked: '探索受阻' })[completion.value.status] || '探索状态未知')
const completionType = computed(() => ({ complete: 'success', needs_targeted_exploration: 'warning', needs_user_decision: 'warning', blocked: 'danger' })[completion.value.status] || 'info')
const attributeText = (attributes) => Object.entries(attributes || {}).map(([key, value]) => `${key}=${value}`).join('，')
const statusText = (status) => ({ confirmed: '已确认', partial: '部分确认', partially_confirmed: '部分确认', unresolved: '未确认' })[status] || status || '未知'
const targetKindLabel = (kind) => ({ observable: '页面可观察项', business_decision: '业务决策', permission_scope: '权限范围', data_scope: '数据范围' })[kind] || '未知'
const formatDuration = (value) => value ? `${Number(value).toFixed(value < 10 ? 1 : 0)} 秒` : '—'
const operationLabel = (operation) => ({ create: '新增', update: '编辑', delete: '删除' })[operation] || '未知'
const operationScopeLabel = (scope) => ({ namespace: '本轮命名空间', user_specified: '用户指定' })[scope] || '未知'
const operationStatusLabel = (status) => ({ observed: '已观察到', unknown: '未知', blocked: '已阻断' })[status] || '未知'
const operationStatusType = (status) => ({ observed: 'success', unknown: 'warning', blocked: 'danger' })[status] || 'info'
const cleanupTitle = computed(() => {
  const detail = cleanup.value.reason ? `：${cleanup.value.reason}` : ''
  if (cleanup.value.status === 'residual') return `发现清理残留，请人工检查${detail}`
  if (cleanup.value.status === 'not_attempted') return `未尝试清理，请人工确认${detail}`
  if (cleanup.value.status === 'unknown') return `清理结果未知，请人工确认${detail}`
  return `${cleanup.value.label}${detail}`
})
</script>

<style scoped>
.evidence-content { display: grid; gap: 18px; }.evidence-section h5 { margin: 0 0 10px; color: var(--app-text-primary); font-size: 14px; }.path-tag { margin: 0 8px 8px 0; }.muted { color: var(--app-text-secondary); font-size: 13px; }.evidence-section p { margin: 6px 0; color: var(--app-text-regular); font-size: 13px; }.evidence-section pre { margin: 8px 0 0; padding: 8px; overflow-x: auto; color: var(--app-text-primary); background: var(--app-bg-secondary, #f7f7f7); border-radius: 6px; font-size: 12px; }.stats { display: flex; flex-wrap: wrap; gap: 12px; color: var(--app-text-secondary); font-size:13px; }.checkpoint, .operation-ledger { padding: 12px; border: 1px solid var(--app-border); border-radius: 8px; }.cleanup-alert { margin-top: 12px; }.cleanup-details { margin-top: 10px; padding: 10px 12px; border-radius: 6px; background: var(--app-bg-secondary, #f7f7f7); }.cleanup-details ul { margin: 6px 0 0; padding-left: 20px; color: var(--app-text-regular); font-size: 13px; line-height: 1.7; }
</style>
