# Generated by Django 4.2.25 on 2026-09-22 09:07

from django.db import migrations, models
import django.db.models.deletion


def backfill_run_participants(apps, schema_editor):
    PerformanceRun = apps.get_model('performance_testing', 'PerformanceRun')
    PerformanceRunNode = apps.get_model('performance_testing', 'PerformanceRunNode')
    status_map = {
        'queued': 'queued',
        'preparing': 'preparing',
        'running': 'running',
        'stopping': 'stopping',
        'completed': 'stopped',
        'cancelled': 'stopped',
        'failed': 'failed',
        'incomplete': 'lost',
    }
    batch = []
    for run in PerformanceRun.objects.all().iterator(chunk_size=500):
        snapshot = run.snapshot if isinstance(run.snapshot, dict) else {}
        raw_users = snapshot.get('users', 1)
        assigned_users = raw_users if type(raw_users) is int and raw_users >= 1 else 1
        batch.append(PerformanceRunNode(
            run_id=run.pk,
            node_id=run.node_id,
            # Historical versions and names were not frozen. Keep them unknown;
            # readers may explicitly fall back to the current related node name.
            node_name='',
            node_agent_version='',
            node_protocol_version=None,
            node_engine_version='',
            assigned_users=assigned_users,
            validation_key=run.validation_key,
            validation_run_id=run.pk if run.mode == 'validation' else None,
            status=status_map.get(run.status, 'failed'),
            node_command=run.node_command,
            node_report=run.node_report,
            node_report_seq=run.node_report_seq,
            started_at=run.started_at,
            reason_code=run.reason_code,
            reason=run.reason,
            latest_metrics=run.latest_metrics,
            metrics_samples=run.metrics_samples,
        ))
        if len(batch) >= 500:
            PerformanceRunNode.objects.bulk_create(batch)
            batch = []
    if batch:
        PerformanceRunNode.objects.bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0004_plan_contract_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRunNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, default='', max_length=200)),
                ('node_agent_version', models.CharField(blank=True, default='', max_length=32)),
                ('node_protocol_version', models.PositiveIntegerField(blank=True, null=True)),
                ('node_engine_version', models.CharField(blank=True, default='', max_length=32)),
                ('assigned_users', models.PositiveIntegerField(default=1)),
                ('validation_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('lost', 'Lost')], default='queued', max_length=20)),
                ('node_command', models.JSONField(blank=True, default=dict, editable=False)),
                ('node_report', models.JSONField(blank=True, default=dict, editable=False)),
                ('node_report_seq', models.PositiveBigIntegerField(default=0, editable=False)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('latest_metrics', models.JSONField(blank=True, default=dict)),
                ('metrics_samples', models.JSONField(blank=True, default=list)),
                ('last_command_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'performance_run_nodes',
                'ordering': ('node_id', 'id'),
            },
        ),
        migrations.AddField(
            model_name='performancerunnode',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='run_participations', to='performance_testing.performancenode'),
        ),
        migrations.AddField(
            model_name='performancerunnode',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='performance_testing.performancerun'),
        ),
        migrations.AddField(
            model_name='performancerunnode',
            name='validation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_participants', to='performance_testing.performancerun'),
        ),
        # Rollback requires restoring the matching pre-release database backup.
        # Choosing one participant would silently discard multi-node evidence.
        migrations.RunPython(backfill_run_participants),
        migrations.RemoveConstraint(
            model_name='performanceplan',
            name='perf_plan_users_1_100',
        ),
        migrations.RemoveField(
            model_name='performancerun',
            name='node',
        ),
        migrations.RemoveField(
            model_name='performancerun',
            name='node_command',
        ),
        migrations.RemoveField(
            model_name='performancerun',
            name='node_report',
        ),
        migrations.RemoveField(
            model_name='performancerun',
            name='node_report_seq',
        ),
        migrations.AddConstraint(
            model_name='performanceplan',
            constraint=models.CheckConstraint(check=models.Q(('users__gte', 1), ('users__lte', 1000)), name='perf_plan_users_1_1000'),
        ),
        migrations.AddIndex(
            model_name='performancerunnode',
            index=models.Index(fields=['node', 'status'], name='perf_runnode_node_status'),
        ),
        migrations.AddConstraint(
            model_name='performancerunnode',
            constraint=models.UniqueConstraint(fields=('run', 'node'), name='perf_run_node_unique'),
        ),
        migrations.AddConstraint(
            model_name='performancerunnode',
            constraint=models.CheckConstraint(check=models.Q(('assigned_users__gte', 1)), name='perf_run_node_users_gte_1'),
        ),
    ]
