# Generated by Django 4.2.25 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0005_performancerunnode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceplan',
            name='connect_timeout_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='performanceplan',
            name='read_timeout_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddConstraint(
            model_name='performanceplan',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('connect_timeout_seconds__gte', 1),
                    ('connect_timeout_seconds__lte', 60),
                ),
                name='perf_plan_connect_timeout_1_60',
            ),
        ),
        migrations.AddConstraint(
            model_name='performanceplan',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('read_timeout_seconds__gte', 1),
                    ('read_timeout_seconds__lte', 120),
                ),
                name='perf_plan_read_timeout_1_120',
            ),
        ),
    ]
