# Generated by Django 4.2.25 on 2026-09-23

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0006_performanceplan_request_timeouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField()),
                ('request_hash', models.CharField(editable=False, max_length=64)),
                ('model_config_id', models.PositiveBigIntegerField(editable=False)),
                ('model_info', models.JSONField(default=dict, editable=False)),
                ('targets', models.JSONField(blank=True, default=dict, editable=False)),
                ('input_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('result', models.JSONField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('celery_task_id', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('queued_deadline_at', models.DateTimeField(editable=False)),
                ('running_deadline_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_analyses', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='performance_testing.performancerun')),
            ],
            options={
                'db_table': 'performance_analyses',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['run', 'status', 'created_at'], name='perf_analysis_run_status')],
                'constraints': [models.UniqueConstraint(fields=('run', 'request_id'), name='perf_analysis_run_request_unique')],
            },
        ),
    ]
