# Generated by Django 4.2.25 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0007_performanceanalysis'),
    ]

    operations = [
        # Existing records retain the original 180-second contract. New rows
        # use 600 seconds after the following state-only default alteration.
        migrations.AddField(
            model_name='performanceanalysis',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=180, editable=False),
        ),
        migrations.AlterField(
            model_name='performanceanalysis',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=600, editable=False),
        ),
        migrations.AddField(
            model_name='performanceanalysis',
            name='progress',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
