# Generated by Django 4.2.25 on 2026-09-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0008_performanceanalysis_timeout_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceanalysis',
            name='analysis_type',
            field=models.CharField(
                choices=[
                    ('load_summary', 'Load summary'),
                    ('validation_diagnosis', 'Validation diagnosis'),
                    ('load_comparison', 'Load comparison'),
                ],
                default='load_summary',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='performanceanalysis',
            name='comparison_run',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='comparison_analyses',
                to='performance_testing.performancerun',
            ),
        ),
        migrations.AddConstraint(
            model_name='performanceanalysis',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(comparison_run__isnull=True)
                    | ~models.Q(run=models.F('comparison_run'))
                ),
                name='perf_analysis_comparison_not_self',
            ),
        ),
        migrations.AddConstraint(
            model_name='performanceanalysis',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(analysis_type='load_comparison')
                    | models.Q(comparison_run__isnull=True)
                ),
                name='perf_analysis_baseline_type',
            ),
        ),
    ]
