# Generated by Django 4.2.25 on 2025-11-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebUITestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="测试用例标题")),
                ("description", models.TextField(verbose_name="测试用例描述")),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="目标URL"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("functional", "功能测试"),
                            ("negative", "异常测试"),
                            ("boundary", "边界测试"),
                            ("security", "安全测试"),
                            ("performance", "性能测试"),
                            ("ui", "界面测试"),
                            ("integration", "集成测试"),
                        ],
                        default="functional",
                        max_length=20,
                        verbose_name="测试类别",
                    ),
                ),
                (
                    "preconditions",
                    models.JSONField(blank=True, default=list, verbose_name="前置条件"),
                ),
                (
                    "steps",
                    models.JSONField(blank=True, default=list, verbose_name="测试步骤"),
                ),
                ("expected_result", models.TextField(verbose_name="预期结果")),
                (
                    "test_script_content",
                    models.TextField(blank=True, null=True, verbose_name="测试脚本内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebUI测试用例",
                "verbose_name_plural": "WebUI测试用例",
                "db_table": "webui_test_cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebUITestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exec_type",
                    models.CharField(
                        choices=[("case", "单用例执行"), ("suite", "套件执行")],
                        max_length=10,
                        verbose_name="执行类型",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="执行名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="执行描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "执行通过"),
                            ("failed", "执行失败"),
                            ("error", "执行错误"),
                            ("stopped", "已停止"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动触发"),
                            ("schedule", "计划任务"),
                            ("api", "API调用"),
                            ("llm", "LLM执行"),
                            ("jenkins", "Jenkins"),
                            ("ci_cd", "CI/CD"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        default="chromium", max_length=20, verbose_name="浏览器类型"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="任务ID"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                (
                    "log_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="日志路径"
                    ),
                ),
                (
                    "report_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="报告路径"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.environment",
                        verbose_name="执行环境",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行者",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebUI测试执行记录",
                "verbose_name_plural": "WebUI测试执行记录",
                "db_table": "webui_test_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebUITestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="测试套件名称")),
                ("description", models.TextField(blank=True, verbose_name="测试套件描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "激活"),
                            ("inactive", "停用"),
                            ("archived", "已归档"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "test_cases",
                    models.ManyToManyField(
                        blank=True,
                        related_name="test_suites",
                        to="web_testing.webuitestcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebUI测试套件",
                "verbose_name_plural": "WebUI测试套件",
                "db_table": "webui_test_suites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebUITestSuiteExecutionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cases",
                    models.PositiveIntegerField(default=0, verbose_name="总用例数"),
                ),
                (
                    "passed_cases",
                    models.PositiveIntegerField(default=0, verbose_name="通过用例数"),
                ),
                (
                    "failed_cases",
                    models.PositiveIntegerField(default=0, verbose_name="失败用例数"),
                ),
                (
                    "skipped_cases",
                    models.PositiveIntegerField(default=0, verbose_name="跳过用例数"),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                (
                    "allure_report",
                    models.TextField(blank=True, null=True, verbose_name="Allure报告路径"),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="执行日志")),
                (
                    "execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suite_execution_detail",
                        to="web_testing.webuitestexecution",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_testing.webuitestsuite",
                        verbose_name="测试套件",
                    ),
                ),
            ],
            options={
                "verbose_name": "套件执行详情",
                "verbose_name_plural": "套件执行详情",
                "db_table": "webui_test_suite_execution_details",
            },
        ),
        migrations.CreateModel(
            name="WebUITestSuiteCaseExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="用例名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "执行通过"),
                            ("failed", "执行失败"),
                            ("error", "执行错误"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="执行日志")),
                (
                    "screenshot_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="截图路径"
                    ),
                ),
                (
                    "video_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="视频路径"
                    ),
                ),
                (
                    "stdout",
                    models.TextField(blank=True, null=True, verbose_name="标准输出"),
                ),
                (
                    "suite_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_executions",
                        to="web_testing.webuitestsuiteexecutiondetail",
                        verbose_name="套件执行详情",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_testing.webuitestcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "套件用例执行明细",
                "verbose_name_plural": "套件用例执行明细",
                "db_table": "webui_test_suite_case_executions",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WebUITestCaseExecutionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "执行通过"),
                            ("failed", "执行失败"),
                            ("error", "执行错误"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="执行日志")),
                (
                    "screenshot_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="截图路径"
                    ),
                ),
                (
                    "video_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="视频路径"
                    ),
                ),
                (
                    "execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_execution_detail",
                        to="web_testing.webuitestexecution",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_testing.webuitestcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "单用例执行详情",
                "verbose_name_plural": "单用例执行详情",
                "db_table": "webui_test_case_execution_details",
            },
        ),
        migrations.CreateModel(
            name="MidSceneScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="脚本名称")),
                ("description", models.TextField(verbose_name="脚本描述")),
                ("script_content", models.TextField(blank=True, verbose_name="脚本内容")),
                ("natural_language", models.TextField(verbose_name="自然语言描述")),
                (
                    "screenshot_b64",
                    models.TextField(blank=True, verbose_name="截图Base64"),
                ),
                (
                    "is_executed",
                    models.BooleanField(default=False, verbose_name="是否已执行"),
                ),
                (
                    "execution_result",
                    models.JSONField(blank=True, default=dict, verbose_name="执行结果"),
                ),
                ("execution_logs", models.TextField(blank=True, verbose_name="执行日志")),
                ("execution_error", models.TextField(blank=True, verbose_name="执行错误")),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Celery任务ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待生成"),
                            ("running", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "生成失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midscene_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midscene_scripts",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "MidScene脚本",
                "verbose_name_plural": "MidScene脚本",
                "db_table": "web_test_midscene_script",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webuitestsuite",
            index=models.Index(
                fields=["user", "project"], name="webui_test__user_id_137f80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webuitestsuite",
            index=models.Index(fields=["status"], name="webui_test__status_f3500f_idx"),
        ),
        migrations.AddIndex(
            model_name="webuitestsuite",
            index=models.Index(
                fields=["created_at"], name="webui_test__created_ec6b8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webuitestcase",
            index=models.Index(
                fields=["user", "project"], name="webui_test__user_id_f4b28c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webuitestcase",
            index=models.Index(
                fields=["category", "priority"], name="webui_test__categor_adfa41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webuitestcase",
            index=models.Index(
                fields=["created_at"], name="webui_test__created_603b28_idx"
            ),
        ),
    ]
