# Generated by Django 4.2.25 on 2026-03-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_knowledgebasefile_status"),
        ("web_testing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebUITestModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="web_testing.webuitestmodule",
                        verbose_name="父模块",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webui_test_modules",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebUI测试模块",
                "verbose_name_plural": "WebUI测试模块",
                "db_table": "webui_test_modules",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="webuitestcase",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_cases",
                to="web_testing.webuitestmodule",
                verbose_name="所属模块",
            ),
        ),
        migrations.AddIndex(
            model_name="webuitestmodule",
            index=models.Index(
                fields=["project", "parent"], name="webui_test__project_456859_idx"
            ),
        ),
    ]
