# Generated by Django 4.2.25 on 2026-03-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_knowledgebasefile_status"),
        ("web_testing", "0002_webuitestmodule_webuitestcase_module_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="页面名称")),
                (
                    "url_path",
                    models.CharField(
                        blank=True, default="/", max_length=500, verbose_name="URL路径"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_pages",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web页面",
                "verbose_name_plural": "Web页面",
                "db_table": "webui_web_pages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="元素名称")),
                (
                    "locator_type",
                    models.CharField(
                        default="css", max_length=50, verbose_name="定位器类型"
                    ),
                ),
                (
                    "locator_value",
                    models.CharField(max_length=500, verbose_name="定位器值"),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="推荐操作类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="web_testing.webpage",
                        verbose_name="所属页面",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web元素",
                "verbose_name_plural": "Web元素",
                "db_table": "webui_web_elements",
                "ordering": ["page", "name"],
            },
        ),
    ]
