# Generated by Django 4.2.25 on 2026-03-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_testing", "0005_add_pom_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="webuitestcase",
            name="last_error_message",
            field=models.TextField(blank=True, null=True, verbose_name="最新错误信息"),
        ),
        migrations.AddField(
            model_name="webuitestcase",
            name="last_execute_status",
            field=models.CharField(
                default="untested", max_length=20, verbose_name="最新执行状态"
            ),
        ),
        migrations.AddField(
            model_name="webuitestcase",
            name="last_execute_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最新执行时间"
            ),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="generated_class_code",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="生成的 Page 类代码（Page 库，兼容旧版）",
            ),
        ),
    ]
