# Generated by Django 4.2.25 on 2026-03-10 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_knowledgebasefile_status"),
        ("web_testing", "0006_webuitestcase_last_error_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="模块名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="模块描述"),
                ),
                (
                    "business_rules",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="业务约束规则"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_modules",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "业务模块",
                "verbose_name_plural": "业务模块",
                "db_table": "test_module",
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="webpage",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pages",
                to="web_testing.testmodule",
                verbose_name="所属模块",
            ),
        ),
    ]
