# Generated by Django 4.2.25 on 2026-08-30 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_alter_project_project_type'),
        ('web_testing', '0012_webuiscriptgeneration_resume_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUITestCaseGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Celery 任务 ID')),
                ('status', models.CharField(choices=[('created', '已创建'), ('context_building', '准备资料中'), ('generating', '生成草稿中'), ('validating', '校验草稿中'), ('repairing', '修复草稿中'), ('needs_review', '待人工审核'), ('importing', '导入中'), ('imported', '已导入'), ('failed', '生成失败'), ('cancelled', '已取消')], db_index=True, default='created', max_length=30, verbose_name='生成状态')),
                ('request_text', models.TextField(blank=True, default='', verbose_name='脱敏场景描述')),
                ('generation_scope', models.CharField(choices=[('core', '核心流程'), ('specified', '指定场景'), ('module_coverage', '模块覆盖')], default='core', max_length=30, verbose_name='生成范围')),
                ('case_categories', models.JSONField(blank=True, default=list, verbose_name='用例类型')),
                ('target_case_count', models.PositiveSmallIntegerField(default=6, verbose_name='目标用例数量')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, verbose_name='脱敏上下文快照')),
                ('draft_test_cases', models.JSONField(blank=True, default=list, verbose_name='测试用例草稿')),
                ('validation_report', models.JSONField(blank=True, default=dict, verbose_name='草稿校验报告')),
                ('created_case_ids', models.JSONField(blank=True, default=list, verbose_name='已导入用例 ID')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='稳定错误码')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='用户可读错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'WebUI 需求用例生成记录',
                'verbose_name_plural': 'WebUI 需求用例生成记录',
                'db_table': 'webui_test_case_generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='webuitestcase',
            name='source_draft_key',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='需求草稿幂等键'),
        ),
        migrations.AddField(
            model_name='webuitestcasegeneration',
            name='model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webui_test_case_generations', to='ai_core.llmconfiguration', verbose_name='使用模型'),
        ),
        migrations.AddField(
            model_name='webuitestcasegeneration',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_generations', to='web_testing.webuitestmodule', verbose_name='锁定业务模块'),
        ),
        migrations.AddField(
            model_name='webuitestcasegeneration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webui_test_case_generations', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='webuitestcasegeneration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webui_test_case_generations', to=settings.AUTH_USER_MODEL, verbose_name='发起用户'),
        ),
        migrations.AddField(
            model_name='webuitestcase',
            name='source_requirement_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_test_cases', to='web_testing.webuitestcasegeneration', verbose_name='需求生成记录'),
        ),
        migrations.AddConstraint(
            model_name='webuitestcase',
            constraint=models.UniqueConstraint(fields=('source_requirement_generation', 'source_draft_key'), name='unique_webui_requirement_draft'),
        ),
        migrations.AddIndex(
            model_name='webuitestcasegeneration',
            index=models.Index(fields=['project', '-created_at'], name='webui_req_project_created'),
        ),
        migrations.AddIndex(
            model_name='webuitestcasegeneration',
            index=models.Index(fields=['user', 'status'], name='webui_req_user_status'),
        ),
    ]
