# Generated by Django 4.2.25 on 2026-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_testing', '0013_webui_requirement_generation_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuitestcasegeneration',
            name='client_request_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='客户端幂等请求 ID'),
        ),
    ]
