# Generated by Django 4.2.25 on 2026-09-06 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_alter_project_project_type'),
        ('web_testing', '0021_native_execution_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuitestcaseexecutiondetail',
            name='execution_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='运行选项快照'),
        ),
        migrations.AddField(
            model_name='webuitestcaseexecutiondetail',
            name='runtime_variable_names',
            field=models.JSONField(blank=True, default=list, verbose_name='一次性运行变量名快照'),
        ),
        migrations.AddField(
            model_name='webuitestcaseexecutiondetail',
            name='source_edit_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='用例编辑版本快照'),
        ),
        migrations.AddField(
            model_name='webuitestcaseexecutiondetail',
            name='source_script',
            field=models.TextField(blank=True, default='', verbose_name='执行脚本快照'),
        ),
        migrations.AddField(
            model_name='webuitestcaseexecutiondetail',
            name='source_script_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='执行脚本版本快照'),
        ),
        migrations.AddField(
            model_name='webuitestcaseexecutiondetail',
            name='source_variables',
            field=models.JSONField(blank=True, default=list, verbose_name='默认变量快照'),
        ),
        migrations.AddField(
            model_name='webuitestsuitecaseexecution',
            name='source_edit_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='用例编辑版本快照'),
        ),
        migrations.AddField(
            model_name='webuitestsuitecaseexecution',
            name='source_script_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='用例脚本版本快照'),
        ),
        migrations.AddField(
            model_name='webuitestsuiteexecutiondetail',
            name='runtime_variable_names',
            field=models.JSONField(blank=True, default=list, verbose_name='一次性运行变量名快照'),
        ),
        migrations.AddField(
            model_name='webuitestsuiteexecutiondetail',
            name='execution_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='运行选项快照'),
        ),
        migrations.CreateModel(
            name='WebUIScriptAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('edit', '编辑'), ('repair', '修复')], max_length=12)),
                ('model_config_id', models.PositiveIntegerField()),
                ('model_info', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('idle', '空闲'), ('queued', '已排队'), ('running', '运行中'), ('candidate_ready', '候选已就绪'), ('candidate_passed', '候选已通过'), ('failed', '失败'), ('cancelled', '已取消'), ('applied', '已采用')], default='idle', max_length=24)),
                ('operation', models.CharField(default='edit', max_length=12)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('phase', models.CharField(blank=True, default='', max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, default='', max_length=100)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('source_script', models.TextField(blank=True, default='')),
                ('source_script_version', models.PositiveIntegerField(blank=True, null=True)),
                ('source_edit_version', models.CharField(blank=True, default='', max_length=64)),
                ('source_variables', models.JSONField(blank=True, default=list)),
                ('source_options', models.JSONField(blank=True, default=dict)),
                ('candidate_script', models.TextField(blank=True, default='')),
                ('candidate_hash', models.CharField(blank=True, default='', max_length=64)),
                ('candidate_diff', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('quality_report', models.JSONField(blank=True, default=dict)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('attempts', models.JSONField(blank=True, default=list)),
                ('verification', models.JSONField(blank=True, default=dict)),
                ('pending_script', models.TextField(blank=True, default='')),
                ('pending_description', models.TextField(blank=True, default='')),
                ('pending_variables', models.JSONField(blank=True, default=list)),
                ('pending_message', models.TextField(blank=True, default='')),
                ('pending_use_candidate', models.BooleanField(default=False)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_assistants', to='web_testing.webuitestexecution')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webui_script_assistants', to='projects.project')),
                ('suite_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_assistants', to='web_testing.webuitestsuitecaseexecution')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_assistants', to='web_testing.webuitestcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webui_script_assistants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webui_script_assistants',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', 'user', '-updated_at'], name='webui_asst_proj_user_upd'), models.Index(fields=['status', 'updated_at'], name='webui_asst_status_updated')],
            },
        ),
    ]
