# Generated by Django 4.2.25 on 2026-09-06 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_alter_project_project_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('parse_status', models.CharField(default='pending', max_length=20)),
                ('index_status', models.CharField(default='pending', max_length=20)),
                ('parse_error', models.TextField(blank=True)),
                ('index_error', models.TextField(blank=True)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新的知识问答', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('client_request_id', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=list)),
                ('model_info', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('phase', models.CharField(default='等待任务启动', max_length=100)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('partial_output', models.TextField(blank=True)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('total_timeout_seconds', models.PositiveIntegerField(default=1200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('module', models.CharField(default='未分类', max_length=100)),
                ('test_type', models.CharField(default='正常', max_length=50)),
                ('preconditions', models.JSONField(default=list)),
                ('test_data', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('test_point_ids', models.JSONField(default=list)),
                ('pending_questions', models.JSONField(default=list)),
                ('review_status', models.CharField(default='unreviewed', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_knowledge.knowledgetask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True)),
                ('result_type', models.CharField(blank=True, max_length=30)),
                ('sources', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project_knowledge.knowledgeconversation')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_knowledge.knowledgetask')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(default='requirement', max_length=30)),
                ('module', models.CharField(default='未分类', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project_knowledge.documentrevision')),
                ('knowledge_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.knowledgebasefile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('section_key', models.CharField(max_length=255)),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('location', models.JSONField(default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='project_knowledge.documentrevision')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='project_knowledge.knowledgedocument'),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.uploadedfile'),
        ),
        migrations.AddConstraint(
            model_name='manualtestcase',
            constraint=models.UniqueConstraint(fields=('source_task', 'draft_id'), name='knowledge_case_draft_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgetask',
            constraint=models.UniqueConstraint(fields=('project', 'created_by', 'kind', 'client_request_id'), name='knowledge_task_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('revision', 'ordinal'), name='knowledge_chunk_ordinal_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='knowledge_document_revision_unique'),
        ),
    ]
