# Generated by Django 4.2.25 on 2026-04-10 07:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[("llm", "LLM"), ("vision", "Vision Model")],
                        default="llm",
                        max_length=10,
                        verbose_name="模型类型",
                    ),
                ),
                (
                    "provider",
                    models.CharField(max_length=20, verbose_name="模型提供商"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API密钥"
                    ),
                ),
                (
                    "base_url",
                    models.URLField(blank=True, max_length=500, verbose_name="基础URL"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="模型名称"),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_configurations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI模型配置",
                "verbose_name_plural": "AI模型配置",
                "db_table": "ai_llm_configurations",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MCPConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="MCP配置名称")),
                ("raw_config", models.TextField(verbose_name="原始MCP配置JSON")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_configurations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP配置",
                "verbose_name_plural": "MCP配置",
                "db_table": "ai_mcp_configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RAGConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否为默认配置"),
                ),
                (
                    "vector_db_type",
                    models.CharField(
                        choices=[("chroma", "Chroma"), ("milvus", "Milvus")],
                        default="chroma",
                        max_length=20,
                        verbose_name="向量数据库类型",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="BAAI/bge-large-zh-v1.5",
                        max_length=100,
                        verbose_name="嵌入模型名称",
                    ),
                ),
                (
                    "chunk_size",
                    models.IntegerField(
                        default=1000,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="文本分块大小",
                    ),
                ),
                (
                    "chunk_overlap",
                    models.IntegerField(
                        default=200,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                        verbose_name="文本分块重叠大小",
                    ),
                ),
                (
                    "chroma_persist_directory",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Chroma持久化目录"
                    ),
                ),
                (
                    "milvus_host",
                    models.CharField(
                        default="localhost",
                        max_length=100,
                        verbose_name="Milvus主机地址",
                    ),
                ),
                (
                    "milvus_port",
                    models.IntegerField(
                        default=19530,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="Milvus端口",
                    ),
                ),
                (
                    "milvus_collection_name",
                    models.CharField(
                        default="knowledge_base",
                        max_length=100,
                        verbose_name="Milvus集合名称",
                    ),
                ),
                (
                    "milvus_dim",
                    models.IntegerField(
                        default=1024,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Milvus向量维度",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_configurations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG配置",
                "verbose_name_plural": "RAG配置",
                "db_table": "ai_rag_configurations",
                "ordering": ["-is_default", "-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MCPTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工具名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="工具描述"),
                ),
                (
                    "tool_schema",
                    models.JSONField(default=dict, verbose_name="工具架构"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "mcp_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="ai_core.mcpconfiguration",
                        verbose_name="MCP配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP工具",
                "verbose_name_plural": "MCP工具",
                "db_table": "ai_mcp_tools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LLMUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, verbose_name="输入Token数"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, verbose_name="输出Token数"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="总Token数"),
                ),
                (
                    "response_time",
                    models.FloatField(default=0.0, verbose_name="响应时间(秒)"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "task_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="任务类型"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(blank=True, max_length=100, verbose_name="任务ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="ai_core.llmconfiguration",
                        verbose_name="使用的配置",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM使用日志",
                "verbose_name_plural": "LLM使用日志",
                "db_table": "ai_llm_usage_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="ragconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("created_by", "is_default"),
                name="unique_rag_default_per_user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mcptool",
            unique_together={("name", "mcp_config")},
        ),
    ]
